name: Docker Image creator for sassbot experimental

on:
  push:
    branches: [flexiefae]

jobs:
  build-and-push-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and push image
        run: |
          docker login --username bombg --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/bombg/sassbot:experimental
          docker push ghcr.io/bombg/sassbot:experimental
  build-and-push-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: bombg
          password: ${{ secrets.GH_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/bombg/sassbot:experimental-arm
          platforms: linux/arm64